src/atoms/Icon.jsx

We had the problem that the X icon in the app was not loaded anymore.
Getting rid of `this.mounted` and `state` and using `this.forceUpdate()` circumvented that problem.
I am not sure if this has some other implications, can you check it @mosch?

Fix icon loading

---

doc/reference/atoms/Image.md
doc/reference/molecules/ExpandingTextarea.md
src/molecules/Card/CardOverlayEditor.jsx
src/molecules/ExpandingTextarea.jsx

In IE11 the textarea was not visible, this PR fixes it by providing a min-height.

Set minHeight for ExpandingTextarea

---

src/molecules/Checkbox.jsx
src/molecules/Checkbox.test.js
src/molecules/TextInput.jsx
src/molecules/__snapshots__/Checkbox.test.js.snap

**This changes the background color behaviour introduced in https://github.com/allthings/elements/pull/95**
In #95 the default behavior of Checkbox was changed. It takes the background color from the theme as background color of the ListItem the Checkbox is using. The background color of the theme is also used for the **background the UI elements are placed** on. 
So the change of #95 get's us this default behaviour: 
Only the Checkbox form element now has the default behaviour of having the same color as the background, and this cannot be changed. And changes the behavior of all existing checkboxes. 
I assume this is not what we actually want. My changes allow to pass a _backgroundColor_ as  a prop to the Checkbox and also the TextInput, and they get just passed to the ListItem. …

Allow to pass background color for Checkbox and TextInput

---

doc/reference/atoms/View.md
doc/reference/behaviour/CDNIntlProvider.md
doc/reference/molecules/Card/Card.md
doc/reference/molecules/Checkbox.md
doc/reference/molecules/ExpandingTextarea.md
doc/reference/molecules/Form/Form.md
doc/reference/molecules/Slider.md
doc/reference/molecules/SquareIconButton.md
doc/reference/molecules/TextInput.md
doc/reference/organisms/Hero.md
doc/reference/organisms/TitleBar.md
src/behaviour/CDNIntlProvider.jsx
src/behaviour/ResourceProvider.jsx

Now exporting `loadLanguage` and `RESOURCE_PATH` for easy reuse in synchron server side rendering.
Checklist:

export resource path and loadLanguage

---

doc/reference/behaviour/HorizontalView.md
src/behaviour/HorizontalView.jsx
stories/HorizontalView.jsx
stories/createViewportDecorator.jsx
stories/index.js

Checklist:
HorizontalView is used to Views in a horizontal row, and will do smooth transitions between them.
The HorizontalView will always show the latest item that get's passed in as a children.
So for this, it will only show the SceondItem.
```
<HorizontalView>
<FirstItem />
<SecondItem />
</HorizontalView>
```
To do transitions between the items, you just *pass* in or *remove children*. So if we update the previous example
to be like this, it will transition from the SecondItem to the FirstItem:
```
<HorizontalView>
<FirstItem />
</HorizontalView>
```
The HorizontalView can work perfectly together with React Router. It will allow you
to have smooth transition from one Route to another.
We are building a taco app, because everyone likes tacos. It consists of 3 screens:
An overview of …

Add HorizontalView

---

src/behaviour/CDNIntlProvider.jsx
src/behaviour/CDNIntlProvider.test.jsx
src/behaviour/__snapshots__/CDNIntlProvider.test.jsx.snap

This introduces a new HTML element which renders differently on client and server side (with [hydrate](https://reactjs.org/docs/react-dom.html#hydrate) in mind) to rehydrate the messages.
This needs to happen in the constructor because the IntlProvider implementation does not behave well on prop changes (see https://github.com/yahoo/react-intl/issues/1097#issuecomment-363114792)
Discussion in #176 
Checklist:

Prevent double render of CDNIntlProvider

---

src/atoms/Input.jsx
src/atoms/__snapshots__/Input.test.jsx.snap
src/behaviour/__snapshots__/FormValidityProvider.test.jsx.snap
src/molecules/__snapshots__/TextInput.test.js.snap
stories/FormStory.jsx
stories/index.js

**What has changed?**
* Show checkmark not only when `pattern` is passed but also when `minLength`, `maxLength` or `required` is passed.
* `&:-webkit-autofill ~ div` selector also selected the checkmark and applied `top: 8px` on it. This is solved by using class names on label/checkmark
* Use `opacity` on the checkmark to display/hide it. With this we can use the same technique to display the checkmark when it was autofilled ✌️
* Bonus: pass `required` to `textarea` as per spec it's a valid attribute.
Checklist:

Input checkmark & autofill fixes

---

doc/reference/atoms/View.md
doc/reference/molecules/Collapsible.md
src/molecules/Collapsible.jsx

Documentation creation was failing because of the glamor ...css() calls in the example + it was quite hard to read for the end-user.
Documentation creation is still failing tho since the live-preview package in there is using an older react version which doesnt have the createRef API included - but thats a different story... 😄 
Checklist:

fixing example to re-enable documentation creation + allow readability

---

src/molecules/Checkbox.jsx
src/molecules/__snapshots__/Checkbox.test.js.snap

before: checkbox's name attribute was missing, meaning form did not submit the checkbox's value
after: name is added so form submits checkbox's true/false also
Checklist:

fix: add name to checkbox

---

src/organisms/Typeahead.jsx
src/organisms/Typeahead.test.jsx

- Should only be there if there's a value! The previous implementation was not strict enough.
Checklist:

Fix for the clear icon.

---

src/behaviour/Confirm.jsx
stories/ConfirmStory.jsx

remove nodeToAppendTo param. result: confirm dialog will always appear in the middle of document.body

fix: confirm always append to document.body

---

src/organisms/DateInput.jsx

`DateInput`: Only show clear icon when calendar view is collapsed.

---

src/molecules/Calendar.jsx

This was intended to fix #602 one day - sadly it doesn't work that "easy"....
So for now - I just changed the disabled styling (otherwise it's hard to distinguish between disabled in the past and dates overlapping to the next month for example) and added ColorPalette colors which brigthen/darken accordingly :/
**Before**:
**After**:
Checklist:

Customise Colors for Calendar

---

src/atoms/Icon.jsx

Only warn once in `Icon` about missing ResourceProvider.

---

doc/reference/molecules/Checkbox.md
scripts/__snapshots__/example.test.js.snap
src/molecules/Checkbox.jsx
src/molecules/Checkbox.test.js
src/molecules/__snapshots__/Checkbox.test.js.snap
stories/CheckboxStory.jsx
stories/index.js

A controlled `<Checkbox>` component with inital `checked` prop set to true, didn't change the the value.
There was no differentiation between controlled/uncontrolled values. This is fixed by this PR.
[**Also added a story to demonstrate**](https://deploy-preview-696--allthings-elements.netlify.com/?path=/story/forms--checkbox)
Checklist:

Fix checkbox controlled component

---

src/atoms/Spinner.jsx

fix: SSR error `ReferenceError: window is not defined`. Check `typeof window` before passing in `window.navigation.userAgent` to helper function `isIE11()`
Checklist:

fix: Spinner check typeof window

---

doc/reference/atoms/Input.md
scripts/__snapshots__/example.test.js.snap
src/atoms/Input.jsx
src/atoms/__snapshots__/Input.test.jsx.snap
src/molecules/__snapshots__/TextInput.test.js.snap
src/organisms/Dropdown.jsx
src/organisms/Typeahead.jsx
src/organisms/__snapshots__/Dropdown.test.jsx.snap
src/organisms/__snapshots__/Typeahead.test.jsx.snap

adjust Typeahead and Input to not overlap icons
Checklist:

fix: Padding right on Typeahead and Input

---

src/organisms/Dropdown.jsx
src/organisms/__snapshots__/Dropdown.test.jsx.snap

Fixing the background color in Dropdown input for IE11. See screenshots below:
Before:
After:

set background color on input for IE11

---

src/organisms/Typeahead.jsx
src/organisms/__snapshots__/Typeahead.test.jsx.snap

Typeahead's `Input`'s `hasRightIcon` prop is only true when `clearOnSelect` is true. This should be false.
Checklist:

fix: Typeahead right padding condition wrong

---

src/organisms/Typeahead.jsx
src/organisms/Typeahead.test.jsx
src/organisms/__snapshots__/Typeahead.test.jsx.snap

bug: no right padding is added when an item from the dropdown is selected, leading to overlapping of text and "x" icon
fix: add right padding when item is selected
Checklist:

fix: Typeahead add right padding when item is selected

---

.storybook/webpack.config.js
package.json
src/Dropdown/Dropdown.test.tsx.snap
src/Input/Input.test.tsx.snap
src/Input/Input.tsx
src/SearchableDropdown/SearchableDropdown.test.tsx.snap
src/TextInput/TextInput.test.tsx.snap
src/Typeahead/Typeahead.test.tsx.snap
tsconfig.json
yarn.lock

There is also another rule in cockpit css about IE quirks. 
https://github.com/allthings/cockpit/blob/master/public/static/css-src/style.css#L46
https://developer.mozilla.org/en-US/docs/Web/CSS/%3A%3A-ms-reveal
It is not in the scope of this PR, but maybe that should also be added?
Checklist:

Resolves APP-3810: IE/App: typeahead needs some fixin’

---

package.json
src/Input/Input.tsx
yarn.lock

Checklist:
Fixes that the label is not displayed if an non-empty defaultValue is used on an input.

fix: label for input with set defaultValue

---

src/Dropdown/Dropdown.test.tsx.snap
src/Input/Input.test.tsx.snap
src/Input/Input.tsx
src/SearchableDropdown/SearchableDropdown.test.tsx.snap
src/TextInput/TextInput.test.tsx.snap

Fixes a bug where inputs with a long label where overflowing into the input field itself covering the input text.
Checklist:

fix(app-5278): overflowing input labels don't cover value anymore
