allthings/elements

- src/molecules/List/ChevronRightListItem.jsx
- src/organisms/Hero.jsx
we need this for our 1-column microapps which whould have weird text-size on tablet/desktop views :)
> adding responsive behaviour to text in hero image

- package.json
> chore(package): update eslint-plugin-jest to version 21.3.2

- package.json
> fix(package): update react-broadcast to version 0.6.0

- package.json
> chore(package): update eslint-plugin-jest to version 21.4.1

- package.json
> chore(package): update fs-extra to version 5.0.0

- doc/reference/atoms/Image.md
- doc/reference/molecules/Card/CardOverlayEditor.md
- src/atoms/Image.jsx
- src/atoms/Image.test.js
- src/atoms/__snapshots__/Image.test.js.snap
- yarn.lock
> Add position to Image

- package.json
> chore(package): update eslint-plugin-jest to version 21.5.0

- package.json
> chore(package): update jest to version 22.1.2

- package.json
> chore(package): update eslint-plugin-jest to version 21.7.0

- package.json
- src/behaviour/CDNIntlProvider.jsx
- src/behaviour/CDNIntlProvider.test.jsx
- src/behaviour/__snapshots__/CDNIntlProvider.test.jsx.snap
- yarn.lock
The CDNIntlProvider gets project translation files from CDN and makes them available to use
Checklist:
> Add cdn intl provider

- package.json
- yarn.lock
> chore(package): update prettier to version 1.10.2

- package.json
- src/molecules/Checkbox.jsx
- src/molecules/Checkbox.test.js
- src/molecules/__snapshots__/Checkbox.test.js.snap
> Upgrade checkbox component

- package.json
- src/behaviour/CDNIntlProvider.jsx
- src/behaviour/CDNIntlProvider.test.jsx
- src/behaviour/__snapshots__/CDNIntlProvider.test.jsx.snap
- yarn.lock
Allow injection of cached messages to avoid a refetch.
Checklist:
> Extend the CDNIntlProvider component.

- src/behaviour/CDNIntlProvider.jsx
- src/behaviour/CDNIntlProvider.test.jsx
- src/behaviour/__snapshots__/CDNIntlProvider.test.jsx.snap
- Either `prodution` (default) or `staging`.
Checklist:
> Add stage to the CDNIntlProvider.

- package.json
> chore(package): update eslint-config-logux to version 21.0.0

- src/behaviour/CDNIntlProvider.jsx
- src/behaviour/CDNIntlProvider.test.jsx
- src/behaviour/__snapshots__/CDNIntlProvider.test.jsx.snap
This is especially useful with SSR when an alternative fetch method can be used.
Checklist:
> Add fetchAlternative prop.

- package.json
- src/behaviour/CDNIntlProvider.test.jsx
> Fix cdn intl provider unit test

- package.json
- src/atoms/Icon.jsx
- src/behaviour/CDNIntlProvider.jsx
- src/behaviour/CDNIntlProvider.test.jsx
- yarn.lock
Checklist:
This PR could be - eventually - used as an upgrade to #137 ...
> Switch to cross-fetch 🐍?

- package.json
> chore(package): update eslint-plugin-jest to version 21.13.0

- src/molecules/Checkbox.jsx
- src/molecules/__snapshots__/Checkbox.test.js.snap
> Don't render checkmark in unchecked

- src/molecules/ProfileImage.jsx
create xs size option for profile image 🐭
Checklist:
> add xs option to profile image size

- src/molecules/ProfileImage.jsx
for profileImage component, size param now accepts number for custom diameter
Checklist:
> able to add custom size for profile image

- src/behaviour/HorizontalView.jsx
Fixes https://github.com/allthings/elements/issues/157
> Prevent overflow on HorizontalView

- .buildkite/pipeline.yml
This triggers a new https://developers.allthings.me documentation generation on every push/merge to master.
Checklist:
> adding buildkite pipeline which triggers new documentation build

- src/molecules/Collapsible.jsx
> Collapsible: Set overflow only 'hidden' when collapsed

- stories/HorizontalView.jsx
revert horizontalView storybook back to previous version
> fix: horizontalView storybook

- src/atoms/View.jsx
> Pass array into proptype instead of arguments

- doc/reference/molecules/Collapsible.md
- src/atoms/Icon.jsx
- src/molecules/Collapsible.jsx
- stories/index.js
- yarn.lock
Some minor content updates:
* adding picture icon
* "fixing" documentation build
* some stories restructuring
> Content updates

- src/organisms/Typeahead.jsx
- src/organisms/Typeahead.test.jsx
Checklist:
Live test: https://deploy-preview-350--allthings-elements.netlify.com/?selectedKind=Forms&selectedStory=Typeahead&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
> Add new behavior when using the clear icon ❎.

- src/organisms/Typeahead.jsx
- src/organisms/Typeahead.test.jsx
> Don't show the clear icon in cleared controlled component.

- src/behaviour/Confirm.jsx
- src/molecules/Card/CardButton.jsx
- src/molecules/Card/__snapshots__/CardButton.test.jsx.snap
- src/molecules/ConfirmDialog.jsx
Add ability to press Ok (enter key) and Cancel (esc key) from keyboard for `Confirm` component
Checklist:
> feature: add enter and esc function to confirm dialog

- src/behaviour/Confirm.jsx
- src/molecules/ConfirmDialog.jsx
pass down `...restProps` to `ConfirmDialog` (needed for data-e2e)
Checklist:
> confirm component: pass down all props

- .buildkite/pipeline.yml
> Apply the same changes as #309.

- src/molecules/Button.jsx
- src/molecules/Card/CardButton.jsx
- src/molecules/Card/__snapshots__/CardButton.test.jsx.snap
- src/molecules/FloatingButton.jsx
- src/molecules/__snapshots__/FloatingButton.test.js.snap
Darken the background color by 10% (like we do on the CardButton) on Buttons and FloatingButtons
> Add an easy hover effect to buttons

- src/atoms/Icon.jsx
- src/atoms/Input.jsx
- src/atoms/__snapshots__/Input.test.jsx.snap
- src/behaviour/__snapshots__/NotificationBubbleManager.test.jsx.snap
- src/molecules/__snapshots__/Checkbox.test.js.snap
- src/molecules/__snapshots__/Collapsible.test.js.snap
- src/molecules/__snapshots__/EditableText.test.jsx.snap
- src/molecules/__snapshots__/NotificationBubble.test.js.snap
- src/molecules/__snapshots__/TextInput.test.js.snap
- src/organisms/__snapshots__/Typeahead.test.jsx.snap
- stories/FormStory.jsx
Add possibility to show an icon for an `Input` component. Also fix some things along the way.
This is only done for single line inputs, not sure if multi line ones need it.
[See preview here 🖼](https://deploy-preview-592--allthings-elements.netlify.com/?selectedKind=Forms&selectedStory=Full%20form&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
Checklist:
> Input icon

- src/layouts/SimpleLayout.jsx
- stories/SimpleLayoutStory.jsx
- stories/index.js
- yarn.lock
Do it other ways: It's more reliable and performant.
Checklist:
> add story and do things performant

- scripts/__snapshots__/example.test.js.snap
- scripts/example.test.js
preset 'react is now '@bable/react'
Checklist:
> Test Examples: update preset

- doc/reference/atoms/Icon.md
- src/atoms/Icon.jsx
- src/behaviour/__snapshots__/NotificationBubbleManager.test.jsx.snap
- src/molecules/__snapshots__/NotificationBubble.test.js.snap
This fixes #198 
Implications so far:
* One place in our products which will be affected (It still looks good with the changed size)
Checklist:
> Update default Icon Size

- doc/reference/organisms/DateInput.md
- src/organisms/DateInput.jsx
- stories/FilterStory.jsx
> Add label to `DateInput`

- src/molecules/Button.jsx
- stories/ButtonStory.jsx
This fixes the "make all buttons white" bug in elements....
We should REALLY implement a contrast color checker "soon" into elements.... I'll put it on my todo list....
> Fix white button color on bright backgrounds

- .travis.yml
- package.json
- yarn.lock
chore: resolve vulnerabilities in deps and add `security-check` as travis step
Checklist:
> chore: resolve vulnerabilities in deps

- package.json
- scripts/__snapshots__/example.test.js.snap
- src/molecules/Checkbox.jsx
- src/molecules/PhoneInput.jsx
- src/molecules/__snapshots__/Checkbox.test.js.snap
Added missing cursor:pointer to Checkbox element.
Also fixed PhoneInput being 5px to wide and resizing the viewport.
> Set cursor: pointer to Checkox

- package.json
- yarn.lock
https://nvd.nist.gov/vuln/detail/CVE-2018-16492.
Checklist:
> Add extend to resolutions to fix security audit.

- src/atoms/Spinner.jsx
- src/utils/viewport.js
check for `window` before passing in `userAgent` to check browser
Checklist:
> check for window for isIE11

- doc/reference/organisms/Typeahead.md
- src/organisms/Typeahead.jsx
- src/organisms/Typeahead.test.jsx
- src/organisms/__snapshots__/Typeahead.test.jsx.snap
- stories/TypeaheadStory.jsx
> Add icon to label on typeahead component

- doc/reference/SearchableDropdown.md
- src/SearchableDropdown/SearchableDropdown.test.tsx.snap
- src/SearchableDropdown/SearchableDropdown.tsx
- stories/SearchableDropdownStory.tsx
Refactoring of the initial searchable dropdown component
> Searchable dropdown v2

- src/molecules/FloatingButton.jsx
- src/molecules/__snapshots__/FloatingButton.test.js.snap
https://allthings.atlassian.net/browse/APP-3399
Checklist:
> fix(floating button): fix content not centred in ff/ie

- package.json
- src/atoms/Icon.jsx
- yarn.lock
> feat: add print icons

- package.json
- yarn.lock
> fix security dependency

- package.json
> fix(app-3810): a new patch version

- src/SimpleLayout/SimpleLayout.tsx
Rewrite SimpleLayout to function component and use forwardRef
> SimpleLayout forwardRef

- src/ExpandingTextarea/ExpandingTextarea.tsx
- stories/ChatStory.tsx
> Rewrite ExpandingTextarea

- doc/reference/Text.md
- src/Text/Text.tsx
> Allow numeric font sizes

- src/ConfirmDialog/ConfirmDialog.tsx
> added e2e tags on confirm dialog element for testing

- src/Typeahead/Typeahead.test.tsx
- src/Typeahead/Typeahead.test.tsx.snap
- src/Typeahead/Typeahead.tsx
> fix autocomple in typeahead
